apiVersion: apps/v1
kind: Deployment
metadata:
  name: Secapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Secapp
  template:
    metadata:
      labels:
        app: Secapp
    spec:
      containers:
      - name: Secapp
        image: akashkumarroy/secapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: secapp-svc
spec:
  selector:
    app: secapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
