apiVersion: apps/v1
kind: Deployment
metadata:
  name: secapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secapp-app
  template:
    metadata:
      labels:
        app: secapp-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: my-secapp-app
        image: secappacr.azurecr.io/secappacr/secapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secapp-app
    k8s-app: secapp-app
  name: secapp-app
spec:
  ports:
  - name: port80
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: secapp-app
