apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: akashkumarroy/netflix:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
spec:
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
