apiVersion: apps/v1
kind: Deployment
metadata:
  name: secapp
  namespace: secapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secapp
  template:
    metadata:
      labels:
        app: secapp
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: secapp
        image: docker.io/akashkumarroy/secapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secapp-service
  namespace: secapp
spec:
  ports:
  - name: port80
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: secapp
